audio player props and styling options
draftbit/react-native-jigsaw pull request #529
Opened 2022-10-29 19:27 UTC by gunjankothari

2022-11-01 18:09 UTC, bluerssen commented on packages/core/src/mappings/AudioPlayer.ts
> +      label: "Remanining Track Color",
typo

2022-11-01 19:31 UTC, gunjankothari commented on packages/core/src/mappings/AudioPlayer.ts
> +      label: "Remanining Track Color",
fixed

2022-11-17 14:23 UTC, bluerssen commented
In Draftbit, the default styles set are generating red screens
<img width="474" alt="Screen Shot 2022-11-17 at 8 23 34 AM" src="https://user-images.githubusercontent.com/461963/202471673-aebaa9f0-2ceb-4b7a-946b-03cbe4154a11.png">

2022-11-18 15:51 UTC, bluerssen requested changes
See other comment

2022-12-15 21:41 UTC, bluerssen approved these changes

2022-12-15 21:41 UTC, merged